version: "3"

services:
  backend-test:
    build: ./backend/.
    volumes:
      - ./:/usr/src/
    command: sh -c 'alembic -c backend/alembic.ini upgrade head && python -m backend.src.main'
    restart: always
    ports:
      - "8001:8001"
    env_file:
      - backend/.env
    depends_on:
      - database-test

  database-test:
    image: postgres:latest
    container_name: database_container
    restart: always
    env_file:
      - .env
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
